USE [master]
GO

/****** Object:  Database [LEROSE_DB]    Script Date: 14/6/2020 14:30:12 ******/
CREATE DATABASE [LEROSE_DB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'LEROSE_DB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\LEROSE_DB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'LEROSE_DB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\LEROSE_DB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [LEROSE_DB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [LEROSE_DB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [LEROSE_DB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [LEROSE_DB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [LEROSE_DB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [LEROSE_DB] SET ARITHABORT OFF 
GO

ALTER DATABASE [LEROSE_DB] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [LEROSE_DB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [LEROSE_DB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [LEROSE_DB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [LEROSE_DB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [LEROSE_DB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [LEROSE_DB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [LEROSE_DB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [LEROSE_DB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [LEROSE_DB] SET  ENABLE_BROKER 
GO

ALTER DATABASE [LEROSE_DB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [LEROSE_DB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [LEROSE_DB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [LEROSE_DB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [LEROSE_DB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [LEROSE_DB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [LEROSE_DB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [LEROSE_DB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [LEROSE_DB] SET  MULTI_USER 
GO

ALTER DATABASE [LEROSE_DB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [LEROSE_DB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [LEROSE_DB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [LEROSE_DB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [LEROSE_DB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [LEROSE_DB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [LEROSE_DB] SET  READ_WRITE 
GO

